language: ruby
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec sidekiq -d -L /tmp/sidekiq.log
  - sleep 1
before_install:
  - gem update --system
  - gem install bundler:2.0.1
services:
  - redis-server
  - postgresql
rvm:
  - 2.6.0
